#!/usr/bin/env python
#  (C) 2017  Paolo Patruno <p.patruno@iperbole.bologna.it>.

import os
import pyonenet.settings
os.environ['DJANGO_SETTINGS_MODULE'] = 'pyonenet.settings'
from django.conf import settings

from pyonenet import daemon
from pyonenet import __version__
from django.core import management
import pyonenet.pyonenet_config



pyonenetweb = daemon.Daemon(
        stdin="/dev/null",
        stdout=pyonenet.settings.logfileweb,
        stderr=pyonenet.settings.errfileweb,
        pidfile=pyonenet.settings.lockfileweb,
        user=pyonenet.settings.userweb,
        group=pyonenet.settings.groupweb
)


#class  mydaemon(daemon):
#
#    def optionparser(self):
#        op = super(miodaemon, self).optionparser()
#        op.add_option("-s", "--syncdb",action="store_false")
#        return op 	  				 


def main(cwd):

    import os
    import django
    django.setup()
    try:
        os.chdir(cwd)
    except:
        pass


    management.call_command("runserver",pyonenet.settings.port,use_reloader=False)


if __name__ == '__main__':

    import sys, os
    cwd=os.getcwd()

    if pyonenetweb.service():

        sys.stdout.write("Pyonenetweb version "+__version__+"\n")
        sys.stdout.write("Daemon started with pid %d\n" % os.getpid())
        sys.stdout.write("Daemon stdout output\n")
        sys.stderr.write("Daemon stderr output\n")

        sys.exit(main(cwd))  # (this code was run as script)
