# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pyonenet.oncron.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onenet', '0003_auto_20170612_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientgroup', models.CharField(max_length=200, verbose_name='Group name')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('clients', models.ManyToManyField(to='onenet.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Configure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezione', models.CharField(default=b'event', editable=False, max_length=50, unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activate Events')),
                ('event_starttime', models.TimeField(verbose_name='Event start time')),
                ('event_endtime', models.TimeField(verbose_name='Event start time')),
            ],
        ),
        migrations.CreateModel(
            name='Eventset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventset', models.CharField(max_length=200, verbose_name='Event name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('pin0onoff', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[pyonenet.oncron.models.validate_onoff], verbose_name='Pin 0 onoff')),
                ('pin1onoff', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[pyonenet.oncron.models.validate_onoff], verbose_name='Pin 1 onoff')),
                ('pin2onoff', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[pyonenet.oncron.models.validate_onoff], verbose_name='Pin 2 onoff')),
                ('pin3onoff', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[pyonenet.oncron.models.validate_onoff], verbose_name='Pin 3 onoff')),
                ('clientgroups', models.ManyToManyField(to='oncron.Clientgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Giorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Programmed start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Programmed end date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Programmed time')),
                ('event_done', models.DateTimeField(editable=False, null=True, verbose_name='Event done')),
                ('eventset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncron.Eventset', verbose_name='refer to Eventset:')),
                ('giorni', models.ManyToManyField(blank=True, to='oncron.Giorno', verbose_name='Programmed days')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Programmed date')),
                ('event_done', models.DateTimeField(editable=False, null=True, verbose_name='Event done')),
                ('eventset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncron.Eventset', verbose_name='refer to Eventset:')),
            ],
        ),
    ]
