# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onenet', '0002_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last action description'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lasttransaction',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data ultima transazione'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Open data'),
        ),
    ]
